"""add_phone_hash_and_email

Revision ID: 1ffcfedd4314
Revises: 721b3883fbc5
Create Date: 2026-03-20 11:30:53.187659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ffcfedd4314'
down_revision: Union[str, Sequence[str], None] = '721b3883fbc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone_hash', sa.String(length=64), nullable=False))
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_unique_constraint(None, 'customers', ['phone_hash'])
    op.drop_index(op.f('ix_menu_items_restaurant_category'), table_name='menu_items')
    op.drop_index(op.f('ix_order_items_order'), table_name='order_items')
    op.drop_index(op.f('ix_orders_restaurant_created'), table_name='orders')
    op.create_unique_constraint(None, 'staff', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='unique')
    op.create_index(op.f('ix_orders_restaurant_created'), 'orders', ['restaurant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_order_items_order'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_menu_items_restaurant_category'), 'menu_items', ['restaurant_id', 'category_id', 'is_available'], unique=False)
    op.drop_constraint(None, 'customers', type_='unique')
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone_encrypted'], unique=False)
    op.drop_column('customers', 'phone_hash')
    # ### end Alembic commands ###
