"""add_buffer_fields

Revision ID: 9373fddd2889
Revises: 5101f36fbea7
Create Date: 2026-03-26 10:39:06.077499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9373fddd2889'
down_revision: Union[str, Sequence[str], None] = '5101f36fbea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: add columns safely
    op.add_column('orders', sa.Column('buffer_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('is_locked', sa.Boolean(), nullable=True))

    # Step 2: populate existing rows
    op.execute("UPDATE orders SET is_locked = FALSE")

    # Step 3: enforce NOT NULL
    op.alter_column('orders', 'is_locked', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_locked')
    op.drop_column('orders', 'buffer_expires_at')
    # ### end Alembic commands ###
